pan:
  ID: 7
  Return_Delay_Time: 0
  Operating_Mode : 4
  LED : 1
  Torque_Enable : 0 # does not work Torque_Enable from yaml file
  # Max_Position_Limit : 4095
  # Min_Position_Limit : 0
tilt:
  ID: 8
  Return_Delay_Time: 0
  Operating_Mode : 4
  LED : 1
  Torque_Enable : 1
  # Max_Position_Limit : 4095
  # Min_Position_Limit : 0



