pan:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode : 4
  LED : 1
  # Goal_Current : 0
  # Torque_Enable : 0 # does not work Torque_Enable from yaml file
  # Max_Position_Limit : 4095
  # Min_Position_Limit : 0
tilt:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode : 4
  LED : 1
  # Torque_Enable : 1
  # Max_Position_Limit : 4095
  # Min_Position_Limit : 0



